'use client';
import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import type { WebsitePage } from '@/types/database';
export function WebsiteManager({organizationId, profileId, initialPages, canEdit, canPublish}:{organizationId:string;profileId:string;initialPages:WebsitePage[];canEdit:boolean;canPublish:boolean}) {const [pages,setPages]=useState(initialPages),[editing,setEditing]=useState<WebsitePage|null>(null),[error,setError]=useState(''); const supabase=createClient();
 async function save(f:FormData){const title=String(f.get('title')), body=String(f.get('body')), slug=String(f.get('slug')).toLowerCase().replace(/[^a-z0-9-]/g,'-'); let result; if(editing) result=await supabase.from('website_pages').update({title,body,slug,status:'DRAFT'}).eq('id',editing.id).select().single(); else result=await supabase.from('website_pages').insert({organization_id:organizationId,created_by:profileId,title,body,slug,section_key:'custom',status:'DRAFT',visibility:'PUBLIC'}).select().single(); if(result.error){setError(result.error.message);return} setPages(editing?pages.map(p=>p.id===editing.id?result.data as WebsitePage:p):[result.data as WebsitePage,...pages]);setEditing(null); }
 async function transition(p:WebsitePage,status:'REVIEW'|'PUBLISHED'){const patch:any={status};if(status==='PUBLISHED')patch.published_at=new Date().toISOString();const {data,error}=await supabase.from('website_pages').update(patch).eq('id',p.id).select().single();if(error){setError(error.message);return}setPages(pages.map(x=>x.id===p.id?data as WebsitePage:x));}
 return <div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2 space-y-3">{pages.length===0&&<div className="rounded-lg border border-dashed p-10 text-center text-sm text-muted-foreground">No pages yet. Start a draft for your public site.</div>}{pages.map(p=><article key={p.id} className="rounded-lg border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{p.title||'Untitled page'}</h3><p className="text-xs text-muted-foreground">/{p.slug} · updated {new Date(p.updated_at).toLocaleDateString()}</p></div><Badge variant={p.status==='PUBLISHED'?'success':p.status==='REVIEW'?'warning':'muted'}>{p.status.toLowerCase()}</Badge></div><p className="mt-3 line-clamp-2 text-sm text-muted-foreground">{p.body||'No content added.'}</p>{canEdit&&<div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing(p)}>Edit draft</Button>{p.status==='DRAFT'&&<Button size="sm" variant="outline" onClick={()=>transition(p,'REVIEW')}>Send for review</Button>}{p.status==='REVIEW'&&canPublish&&<Button size="sm" onClick={()=>transition(p,'PUBLISHED')}>Publish</Button>}</div>}</article>)}</section>{canEdit&&<aside className="rounded-lg border bg-card p-5"><h2 className="font-semibold">{editing?'Edit draft':'New page'}</h2><p className="mb-4 mt-1 text-sm text-muted-foreground">Draft → review → publish keeps every change intentional.</p><form action={save} className="space-y-3"><div><Label>Title</Label><Input name="title" defaultValue={editing?.title??''} required/></div><div><Label>URL slug</Label><Input name="slug" defaultValue={editing?.slug??''} placeholder="club-history" required/></div><div><Label>Page content</Label><Textarea name="body" defaultValue={editing?.body??''} className="min-h-40" required/></div>{error&&<p className="text-xs text-destructive">{error}</p>}<div className="flex gap-2"><Button>{editing?'Save as draft':'Create draft'}</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button>}</div></form></aside>}</div>}
